version: '3'

services:
  elaastic-questions-db:
    image: mysql:5
    container_name: elaastic-questions-db
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6603:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-server-standalone:
    build:
      context: .
    image: elaastic-questions-server-standalone:latest
    container_name: elaastic-questions-server
    depends_on:
      - elaastic-questions-db
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=elaastic-questions-db
      - DATABASE_USER=elaastic
      - DATABASE_NAME=elaastic-questions
      - DATABASE_PASSWORD=elaastic
      - DATABASE_PORT=3306
