version: '3'

services:
  elaastic-questions-db:
    image: mysql:8.0
    container_name: elaastic-questions-db
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6603:3306
  elaastic-questions-server:
    image: org.elaastic.questions/elaastic-questions-server:latest
    container_name: elaastic-questions-server
    depends_on:
      - elaastic-questions-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=elaastic-questions-db
      - DATABASE_USER=elaastic
      - DATABASE_NAME=elaastic-questions
      - DATABASE_PASSWORD=elaastic
      - DATABASE_PORT=3306