version: '3'

services:
  elaastic-questions-db:
    image: mysql:5
    container_name: elaastic-questions-db
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6603:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-db-test:
    image: mysql:5
    container_name: elaastic-questions-db-test
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions-test
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6604:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
