version: '3'

services:
  elaastic-questions-db:
    image: mysql:5
    container_name: elaastic-questions-db
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6603:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-tomcat:
    build:
      context: ./docker-resources/tomcat
    image: elaastic-tomcat
    container_name: elaastic-tomcat
    depends_on:
      - elaastic-questions-db
    ports:
      - 8088:8080
    volumes:
      - ./build/libs/elaastic-questions-server-5.1.4.war:/usr/local/tomcat/webapps/elaastic-questions.war
