version: '3'

services:
  elaastic-questions-db-8:
    image: mysql:8
    container_name: elaastic-questions-db-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6683:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-server-standalone:
    build:
      context: .
    image: elaastic-questions-server-standalone:latest
    container_name: elaastic-questions-server
    depends_on:
      - elaastic-questions-db-8
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=elaastic-questions-db-8
      - DATABASE_USER=elaastic
      - DATABASE_NAME=elaastic-questions
      - DATABASE_PASSWORD=elaastic
      - DATABASE_PORT=3306
